## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Build
        run: ./gradlew build --console=plain

      - name: Install Native Image (if needed)
        run: |
            sudo apt-get install -y gcc
            ./gradlew quarkusBuild --console=plain

      - name: Build Native Image (if needed)
        run: |
            ./gradlew buildNative --console=plain

      - name: Deploy to Docker Hub
        run: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker build -t nhatuan444/tracker:latest .
            docker push nhatuan444/tracker:latest