## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Build
        run: ./gradlew build --console=plain

      - name: Set up Docker Buildx (optional)
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker buildx build -t nhatuan444/tracker:latest -f src/main/docker/Dockerfile.jvm

      - name: Log in to Docker Registry
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin nhatuan444

      - name: Push Docker Image
        run: docker push nhatuan444/tracker:latest